import 'package:flutter/cupertino.dart';
import 'dart:ui' as ui;

/// Represents the behavior of the shapes generated by the library, along with all the necessary data defining their characteristics.
///
/// When creating an instance of this class, provide the following parameters:
///
/// - [shape] An object of type [ShapeType] that specifies the structure of the shape.
/// - [icon] If [shape] is set to [ShapeType.Icon], you must pass an [IconData] object to this field.
/// - [image] If [shape] is set to [ShapeType.Image], you need to provide a [ui.Image] object to this field.
class ItemBehaviour {
  ShapeType shape;
  IconData? icon;
  ui.Image? image;

  ItemBehaviour({required this.shape, this.icon, this.image});
}

/// Enumerates various types of shapes that the library can handle.
///
/// Use this enum to specify the type of shape when working with the library's functionality.
enum ShapeType {
  FilledCircle,
  StrokeCircle,
  DoubleStrokeCircle,
  TripleStrokeCircle,
  FilledSquare,
  StrokeSquare,
  DoubleStrokeSquare,
  TripleStrokeSquare,
  Icon,
  Image,
}
